name: Release to AUR

on:
  push:
    paths:
      - 'dist/regular/**'
      - 'dist/cn/**'
      - '.github/workflows/aur-release.yml'

jobs:
  aur-release:
    runs-on: ubuntu-latest
    env:
      AUR_EMAIL: ${{ secrets.AUR_EMAIL }}
      GIT_AUTHOR_NAME: github-actions[bot]
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
      GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 aur.archlinux.org >> ~/.ssh/known_hosts

      - name: Push monika-after-story-cn to AUR
        run: |
          git clone ssh://aur@aur.archlinux.org/monika-after-story-cn.git aur-cn
          rsync -av --delete dist/cn/ aur-cn/
          cd aur-cn
          makepkg --printsrcinfo > .SRCINFO
          git add .
          git diff --cached --quiet || git commit -m "auto: update from GitHub Actions"
          git push

      - name: Push monika-after-story to AUR
        run: |
          git clone ssh://aur@aur.archlinux.org/monika-after-story.git aur-regular
          rsync -av --delete dist/regular/ aur-regular/
          cd aur-regular
          makepkg --printsrcinfo > .SRCINFO
          git add .
          git diff --cached --quiet || git commit -m "auto: update from GitHub Actions"
          git push